name: flutter_scaffold
description: To be able to generate file structure
version: 0.0.12
author: Ganesh Hegde<nshganesh@gmail.com>
homepage: https://github.com/nshganesh/flutter_scaffold.git

environment:
  sdk: ">=2.1.0 <3.0.0"

executables:
  flutter_scaffold:

dependencies:
  args: ^1.5.2
  meta: ^1.1.8
  mustache: ^1.1.1
  recase: ^2.0.1
  resource: ^2.1.6
